# Generated by Django 4.1.1 on 2022-09-27 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('places', '0001_initial'),
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='advertisement_image')),
                ('price', models.PositiveBigIntegerField(verbose_name='Цена')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currency_buy', to='settings.currency', verbose_name='Название валюты')),
                ('slug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='place_slug', to='places.places', verbose_name='Местоположение')),
            ],
            options={
                'verbose_name': 'Отель',
                'verbose_name_plural': 'Отели',
            },
        ),
    ]
