# Generated by Django 4.1.1 on 2022-09-29 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0003_rename_slug_hotel_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='Сategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_count', models.PositiveIntegerField(verbose_name='Количество дней')),
                ('people', models.PositiveIntegerField(verbose_name='Количество людей')),
                ('clas', models.CharField(max_length=255, verbose_name='Класс')),
            ],
        ),
    ]
