# Generated by Django 4.1.1 on 2022-09-30 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0004_сategories'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clas', models.CharField(max_length=255, verbose_name='Класс номера')),
            ],
            options={
                'verbose_name': 'Класс номера',
                'verbose_name_plural': 'Класс номеров',
            },
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('people', models.CharField(max_length=255, verbose_name='Тип бронирование')),
            ],
            options={
                'verbose_name': 'Тип бронирование',
                'verbose_name_plural': 'Тип бронирование',
            },
        ),
        migrations.DeleteModel(
            name='Сategories',
        ),
    ]
