# Generated by Django 4.1.1 on 2022-10-02 06:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hotels', '0005_class_people_delete_сategories'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date1', models.CharField(max_length=255, verbose_name='дата отправки')),
                ('date2', models.CharField(max_length=255, verbose_name='дата отезда')),
                ('clas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_hotel', to='hotels.class', verbose_name='Класс')),
                ('people', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='people_hotel', to='hotels.people', verbose_name='Количество людей')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_booking', to=settings.AUTH_USER_MODEL, verbose_name='Заказшик')),
            ],
        ),
    ]
