# Generated by Django 4.1.1 on 2022-10-03 10:22

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hotels', '0009_сomments'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Сomments',
            new_name='Comments',
        ),
    ]
