# Generated by Django 4.1.1 on 2022-10-10 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0011_comments_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='description',
            field=models.TextField(verbose_name='Описание отеля'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='image',
            field=models.ImageField(upload_to='advertisement_image', verbose_name='Фотография отеля'),
        ),
    ]
