# Generated by Django 4.1.1 on 2022-10-09 17:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work_us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_us', to=settings.AUTH_USER_MODEL, verbose_name='Пользовател')),
            ],
            options={
                'verbose_name': 'Пользователь работаюшии на нас',
                'verbose_name_plural': 'Пользователь работаюшие на нас',
            },
        ),
    ]
