# Generated by Django 4.1.1 on 2022-10-10 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_work_us'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='balans',
            field=models.PositiveBigIntegerField(default=1, verbose_name='Баланс'),
            preserve_default=False,
        ),
    ]
