# Generated by Django 4.1.1 on 2022-10-10 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_balans'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='balans',
            field=models.PositiveBigIntegerField(default=0, verbose_name='Баланс'),
        ),
    ]
