# Generated by Django 4.1.1 on 2022-09-27 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('countries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Places',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(verbose_name='Название места')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
            },
        ),
        migrations.CreateModel(
            name='Places_for_rest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image_rest', models.ImageField(upload_to='advertisement_image')),
                ('nation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nation', to='countries.nation', verbose_name='Страна')),
                ('slug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slug_place', to='places.places', verbose_name='Название места')),
            ],
            options={
                'verbose_name': 'Места для отдыха',
                'verbose_name_plural': 'Места для отдыха',
            },
        ),
    ]
