# Generated by Django 4.1.1 on 2022-09-29 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='places',
            name='title',
            field=models.CharField(default=1, max_length=255, verbose_name='Название места'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='places',
            name='slug',
            field=models.SlugField(verbose_name='Слаг места'),
        ),
    ]
