# Generated by Django 4.1.1 on 2022-10-10 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_places_title_alter_places_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='places_for_rest',
            name='description',
        ),
    ]
