# Generated by Django 4.1.1 on 2022-09-27 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nation_name', models.CharField(max_length=255, verbose_name='Страны')),
            ],
            options={
                'verbose_name': 'Страна',
                'verbose_name_plural': 'Cтраны',
            },
        ),
    ]
